repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: fix-encoding-pragma

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.8.4'
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix, --ignore=F821]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0
    hooks:
      - id: markdownlint-fix
        # MD013: line too long
        args: [--disable, MD013, "--"]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.30.0
    hooks:
      - id: check-dependabot
        args: ["--verbose"]
      - id: check-github-workflows
        args: ["--verbose"]
