name: Publish book

description: "Publish book to a branch"

on:
  workflow_call:
    inputs:
      target-branch:
        description: 'Target branch'
        type: string
        required: true
        default: 'gh-pages'

runs:
  using: "composite"
  steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      #  Build the book
      - name: Build the book
        shell: bash
        run: |
          make build

      - uses: actions/cache@v3
        name: Jupyter Cache
        with:
          path: book/_build/.jupyter_cache
          key: ${{ runner.os }}-jupyter-${{ hashFiles('**/*') }}
          restore-keys: |
            ${{ runner.os }}-jupyter-

      # Push the book's HTML to draft
      - name: GitHub Pages action
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
            branch: ${{ inputs.target-branch }} # The branch the action should deploy to.
            folder: book/_build/html # The folder the action should deploy.
