name: deploy-book

on:
  push:
    branches:
      - main

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Install dependencies
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install jupyterbook
      run: |
        pip install -r requirements.txt
        pip install jupyter-book

    # Build the book
    - name: Build the book
      run: |
        jupyter-book clean book
        jupyter-book build book
        touch book/_build/html/.nojekyll

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
          branch: gh-pages # The branch the action should deploy to.
          folder: book/_build/html # The folder the action should deploy.
